# test
services:
    mysqldb:
      image: mysql:5.7
      restart: unless-stopped
      platform: linux/x86_64
      environment:
        # PUT YOUR MYSQL DATABASE PASSWORD
        - MYSQL_ROOT_PASSWORD=123456
        - MYSQL_DATABASE=todo
      ports:
        - 3307:3306
      volumes:
        - db:/var/lib/mysql
      networks:
        - server-network
    nodejs:
      depends_on:
        - mysqldb
      build: server/
      restart: unless-stopped
      ports:
        - 8080:8080
      environment:
          - DB_HOST=mysqldb
          - DB_USER=root
          # PUT YOUR MYSQL DATABASE PASSWORD BELOW
          - DB_PASSWORD=123456
          - DB_NAME=todo
          - DB_LOCAL_PORT=3307
          - DB_PORT=3306
          - WEB_PORT=8080
          # PUT YOUR JAVASCRIPT WEB TOKEN SECRET BELOW
          - JWT_SECRET=secret
          # PUT YOUR SITE OWNER ACCOUNT INFO BELOW
          - OWNER_USERNAME=todo-owner
          - OWNER_PASSWORD=password
          - OWNER_EMAIL=sample@email.com
      stdin_open: true
      tty: true
      networks:
        - server-network

volumes:
  db:

networks:
    server-network:
      driver: bridge